//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// This interface defines the contract between the Presenter and its View, following the
// Model-View-Presenter pattern. 
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System.Drawing;
using System;
namespace ScsfDemo.StopLight
{
	public interface IStopLightView
	{
		Color CurrentColor { get; set; }

		string GreenDuration { get; set; }

		string YellowDuration { get; set; }

		string RedDuration { get; set; }

		void SetError(string propertyName, string errorMessage);

		event EventHandler UpdateClicked;

		event EventHandler ForceChangeClicked;

		public static class StoplightViewProperties
		{
			public const string CurrentColor = "CurrentColor";
			public const string GreenDuration = "GreenDuration";
			public const string YellowDuration = "YellowDuration";
			public const string RedDuration = "RedDuration";
		}
	}
}

