
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ScsfDemo.StopLight
{
	partial class StopLightView
	{
		/// <summary>
		/// The presenter used by this view.
		/// </summary>
		private ScsfDemo.StopLight.StopLightViewPresenter _presenter = null;

		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (_presenter != null)
					_presenter.Dispose();

				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.stopLightPanel = new System.Windows.Forms.Panel();
			this.greenDurationTextBox = new System.Windows.Forms.TextBox();
			this.yellowDurationTextBox = new System.Windows.Forms.TextBox();
			this.redDurationTextBox = new System.Windows.Forms.TextBox();
			this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
			((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
			this.SuspendLayout();
			// 
			// stopLightPanel
			// 
			this.stopLightPanel.Location = new System.Drawing.Point(29, 27);
			this.stopLightPanel.Name = "stopLightPanel";
			this.stopLightPanel.Size = new System.Drawing.Size(421, 43);
			this.stopLightPanel.TabIndex = 0;
			// 
			// greenDurationTextBox
			// 
			this.greenDurationTextBox.Location = new System.Drawing.Point(52, 128);
			this.greenDurationTextBox.Name = "greenDurationTextBox";
			this.greenDurationTextBox.Size = new System.Drawing.Size(334, 21);
			this.greenDurationTextBox.TabIndex = 1;
			// 
			// yellowDurationTextBox
			// 
			this.yellowDurationTextBox.Location = new System.Drawing.Point(52, 181);
			this.yellowDurationTextBox.Name = "yellowDurationTextBox";
			this.yellowDurationTextBox.Size = new System.Drawing.Size(334, 21);
			this.yellowDurationTextBox.TabIndex = 1;
			// 
			// redDurationTextBox
			// 
			this.redDurationTextBox.Location = new System.Drawing.Point(52, 250);
			this.redDurationTextBox.Name = "redDurationTextBox";
			this.redDurationTextBox.Size = new System.Drawing.Size(334, 21);
			this.redDurationTextBox.TabIndex = 1;
			// 
			// errorProvider
			// 
			this.errorProvider.ContainerControl = this;
			// 
			// StopLightView
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.redDurationTextBox);
			this.Controls.Add(this.yellowDurationTextBox);
			this.Controls.Add(this.greenDurationTextBox);
			this.Controls.Add(this.stopLightPanel);
			this.Name = "StopLightView";
			this.Size = new System.Drawing.Size(505, 362);
			((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Panel stopLightPanel;
		private System.Windows.Forms.TextBox greenDurationTextBox;
		private System.Windows.Forms.TextBox yellowDurationTextBox;
		private System.Windows.Forms.TextBox redDurationTextBox;
		private System.Windows.Forms.ErrorProvider errorProvider;
	}
}

